"""Add description field to meetingroom model

Revision ID: 57910edcf78d
Revises: 91c49c1df5e2
Create Date: 2023-11-01 14:55:06.749047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57910edcf78d'
down_revision = '91c49c1df5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
